[server]
port = 8125
host = "0.0.0.0"
frontend_url = "http://localhost:5173"  # Development frontend URL, empty in production

[sqlite]
path = "local.db"

[oidc]
# Use explicit URLs for each endpoint instead of discovery
# Provider URL for OIDC discovery - use service name for container-to-container communication
provider_url = "http://dex:5556/dex"
# Browser-facing auth URL - must match the domain/issuer used by DEX for browser communication
auth_url = "http://localhost:5556/dex/auth"
# Internal container-to-container token URL
token_url = "http://dex:5556/dex/token"

client_id = "logchef"
client_secret = "logchef-secret"
# Browser-facing redirect URL
redirect_url = "http://localhost:8125/api/v1/auth/callback"
scopes = ["openid", "email", "profile"]

[auth]
admin_emails = ["admin@logchef.internal"]
session_duration = "24h"
max_concurrent_sessions = 1

[logging]
level = "debug"
